import { Providers } from "@/components"
import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import "./globals.css"

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const bodyCn = `${jetbrainsMono.variable} antialiase`

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={bodyCn} style={{ backgroundColor: "black" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
